use bevy::{prelude::*, utils::HashMap};
use bevy_inspector_egui::egui::TextBuffer;

use super::I18Key;

impl I18Key {
    pub fn spanish(&self) -> String {
        match &self {
            I18Key::AcPopulationGrowingGc => "AC: Población: ¡en aumento! (GC)",
            I18Key::AcCityFolkWii => "AC: Let's Go To The City (Wii)",
            I18Key::AcCityFolkWiiRainy => "AC: Let's Go To The City (Wii) [Lloviendo]",
            I18Key::AcCityFolkWiiSnowy => "AC: Let's Go To The City (Wii) [Nevando]",
            I18Key::AcNewLeaf3ds => "AC: New Leaf (3DS)",
            I18Key::AcNewLeaf3dsRainy => "AC: New Leaf (3DS) [Lloviendo]",
            I18Key::AcNewLeaf3dsSnowy => "AC: New Leaf (3DS) [Nevando]",
            I18Key::AcNewHorizonsSwitch => "AC: New Horizons (Switch)",
            I18Key::KkSlider =>  "Totakeke",
            I18Key::Random =>  "Selección Aleatoria",
            I18Key::MusicVolume =>  "Volumen de Música",
            I18Key::RainVolume =>  "Volumen de Lluvia",
            I18Key::Settings =>  "Ajustes",
            I18Key::Home =>  "Inicio",
            I18Key::MinimizeToTray =>  "Minimizar a la bandeja",
            I18Key::ExitNook =>  "Salir de Nook",
            I18Key::PatreonListAndSupportLinks =>  "Lista de Patreon y enlaces de soporte",
            I18Key::PlayerSettings => "configuración del reproductor",
            I18Key::GrandfatherClockMode => "Modo de reloj de pie",
            I18Key::UseGameRainSound => "Usa el sonido de la lluvia del juego",
            I18Key::UseNoThunderRainSound => "Usar sonido de lluvia sin truenos",
            I18Key::Language => "idioma",
            I18Key::ClearLocalFilesAndSettings => "borrar archivos y configuraciones locales",
            I18Key::PatreonSupporters => "seguidores de patreon",
            I18Key::OpensDevelopersPatreonPage => "Abre la página de Patreon del autor",
            I18Key::SupportMe => "(¡apoyar!)",
            I18Key::GoldSupporters => "partidarios de oro",
            I18Key::SilverSupporters => "partidarios de plata",
            I18Key::BronzeSupporters => "partidarios de bronce",
            I18Key::Patreon => "patreon",
            I18Key::PlaysOnceNoLoop => "(se reproduce una vez, sin bucle)",
            I18Key::AreYouSure => "¿Está seguro?",
            I18Key::ClickOkToProceedAndDeleteAllLocalMusicFilesAndUserSettings => "Haga clic en \"Aceptar\" para continuar y eliminar todos los archivos de música locales y la configuración del usuario.",
            I18Key::Customize => "personalizar",
            I18Key::EnableTownTune => "Habilitar melodía de la ciudad",
            I18Key::TuneSettings => "ajustes de melodía de la ciudad",
            I18Key::Offline =>  "fuera de línea",
            I18Key::OfflineFilesTotalFilesOfflineHourlyMusicFilesDownloaded => "{{offlineFiles}}/{{totalFiles}} archivos de música horária descargados",
            I18Key::OfflineKkfilesTotalKkfilesOfflineKKMusicFilesDownloaded => "{{offlineKKFiles}}/{{totalKKFiles}} archivos de música k.k. descargados",
            I18Key::DownloadAllHourlyMusic => "descargar toda la música horária",
            I18Key::DownloadAllKKMusic => "descargar toda la música k.k.",
            I18Key::SaveLovercase =>  "guardar",
            I18Key::PlayLowercase => "reproducir",
            I18Key::FailedToLoadSound => "no se pudo cargar la música horária.",
            I18Key::FailedToLoadRainSound =>  "no se pudo cargar el sonido de la lluvia.",
            I18Key::Play =>  "Reproducir",
            I18Key::Pause => "Pausar",
            I18Key::FailedToDownload =>  "no se pudo descargar la música.",
            I18Key::AcPopulationGrowingGcSnowy =>  "AC: Población: ¡en aumento! (GC) [Nevando]",
            I18Key::AcPopulationGrowingGcSakura =>  "AC: Población: ¡en aumento! (GC) [Sakura]",
            I18Key::AcNewHorizonsSwitchRainy =>  "AC: New Horizons (Switch) [Lloviendo]",
            I18Key::AcNewHorizonsSwitchSnowy =>  "AC: New Horizons (Switch) [Nevando]",
            I18Key::AcPocketCampMobile =>  "AC: Pocket Camp (Móvil)",
            I18Key::PlayKkMusicOnSaturdayNights =>  "Tocar música K.K. sábados por la noche",
            I18Key::OpenOnStartup =>  "Abrir al iniciar",
            I18Key::CustomizeKKPlaylist => "personalizar la lista de k.k.",
            I18Key::CustomizeTownTune => "personalizar la melodía de la ciudad",
            I18Key::KkPlaylist => "lista de k.k.",
            I18Key::CheckAll => "marque todas",
            I18Key::UncheckAll => "desmarque todas",
            I18Key::RadioOnly => "solo radio",
            I18Key::LiveOnly => "solo en vivo",
            I18Key::Downloading => "descargando...",
            I18Key::DontDownloadMusic => "No descargar",
            I18Key::SavesSpaceButNoOffline =>  "(ahorra espacio, fuera de linea no funcionará)",
            I18Key::TipYouCanUseTheMouseWheelToAdjustNotes => "consejo: puedes usar la rueda del mouse para ajustar las notas",
            I18Key::NookGitHub => "Nook GitHub",
            I18Key::Saved => "guardado!",
            // automatic transalations
            I18Key::Changelog => "registro de cambios",
            I18Key::AcPopulationGrowingGcRainyDay => "AC: Población: ¡en aumento! (GC) [Día de lluvia]",
        }.to_string()
    }
}
